name: udacity backend ci project

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths:
      - "starter/backend/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Pipenv
        working-directory: starter/backend
        run: pip install pipenv

      - name: Install dependencies
        working-directory: starter/backend
        run: pipenv install --dev

      - name: Run Linter
        working-directory: starter/backend
        run: pipenv run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Pipenv
        working-directory: starter/backend
        run: pip install pipenv

      - name: Install dependencies
        working-directory: starter/backend
        run: pipenv install --dev

      - name: Run Test
        working-directory: starter/backend
        run: pipenv run test

  build:
    runs-on: ubuntu-latest
    needs: 
      - lint
      - test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build \
            --tag mp-backend:latest \
            starter/backend
