name: udacity ci project

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths:
      - "starter/frontend/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run linter
        working-directory: starter/frontend
        run: npm run lint

      - name: Run test
        working-directory: starter/frontend
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL=http://localhost:5000 \
            --tag mp-frontend:latest \
            starter/frontend
